### ISSUE TITLE
Ability to set "defaultScene" and "repository" to package.json via CLI

### ISSUE THREAD

**Issue by morfeyc** [nomnomab/create-unity-template#1]

**Comment by nomnomab** [comment]
Hello! After looking at the package.json schema, I am not seeing a `defaultScene` or `repository` field in it. Are you wanting the fields to simply exist for custom usage?

**Comment by morfeyc** [comment]
Hi! Actually, I didn't know that these fields are not present in the scheme by default, but I've seen them in other templates. I think it would be very convenient to at least be able to specify which `scene` will run when creating a project. As for the `repopository` field, it's more of a way to provide more information about the template to their users. I think that it would be very convenient to specify these fields in the `CLI` during creation

**Comment by nomnomab** [comment]
In the new branch you can now define the default scene to run on first boot, and a repository field for reading purposes. Let me know if this is what you wanted!

**Comment by morfeyc** [comment]
Yes, this is exactly what I wanted. Thank you!
